version: '3.8'

services:
  backend:
    build: 
      context: .
      target: backend-builder
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/data
    environment:
      - DATABASE_URL=sqlite:////data/academic.db
    command: uvicorn backend.app:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: .
      target: frontend-builder
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=academic
      - POSTGRES_PASSWORD=academic
      - POSTGRES_DB=academic
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  data: